name: parent
on:
  workflow_dispatch:

jobs:
  greet-windows:
    runs-on: windows-latest
    steps:
    - name: create-file
      run: echo Hello Windows > windows.txt
    - name: 'Store Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: artifact-windows
        path: windows.txt    
        
  greet-macos:
    runs-on: macos-latest
    steps:
    - name: create-file
      run: date > macos.txt
    - name: 'Store Artifact'
      uses: actions/upload-artifact@v3
      with:
        name: artifact-macos
        path: macos.txt      
        
  merge:
    runs-on: macos-latest
    needs: [greet-windows, greet-macos]
    steps:
      - name: Download Windows
        uses: actions/download-artifact@v2.1.1
        with:
          name: artifact-windows
    
      - name: Download MacOS
        uses: actions/download-artifact@v2.1.1
        with:
          name: artifact-macos
    
      - name: Show Files
        run: | 
          find .
          cat windows.txt
          cat macos.txt
        
        
